# Change these first
owner: carlosmathiasen # Your GitHub organization or username, where this repository lives
repo: pinbus-status # The name of this repository

sites:
  - name: API
    url: https://api.pinbus.com
  - name: Page
    url: https://pinbus.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pinbus.com
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.pinbus.com/common/img/pinbus-logo-nav.svg
  name: Pinbus Status
  introTitle: "**Pinbus Status** página de status para pinbus.com"
  introMessage: En esta página se ve el estado actual de los servicios de pinbus.com
  navbar:
    - title: Status
      href: /
    - title: Pinbus.com
      href: https://pinbus.com
status-website:
  themeUrl: https://status.pinbus.com/status-custom.css
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
